### ISSUE TITLE
Project that was working is no longer working

### ISSUE THREAD

**Issue by buschmann** [EpicGames/PixelStreamingInfrastructure#232] opened 2024-08-06 07:41 UTC
[buschmann](https://github.com/buschmann) commented [yesterday](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/168#issuecomment-2268535494)
Good morning ;)

What UE version and PS infra versions are you using?
.. It is UE5.1 and some tiny scripts.

What hardware/VM are you running your project on?
.. It is a dedicated root server, ubuntu 20.04, gnome, x11, with 128gb memory, A4000gpu.

Are you using the default distribution of PS and its components? If not, what changes have you made?
.. How can i check that ? I think that is all anyway hand build for the C++ multiplayer template...

When encountering the issue, please spell out step-by step exactly what you've done and where the issue occurs:
.. Easy to explain, 200 days before i did "start-signal, start-stream" and it was running fine.
We changed nothing in game code or scripts for starting it.
So i GUESS any server updates was fail or missing or a driver update delivered the problem.

Is your project packaged for shipping/development?
.. Oh yes, we have any external "compiler" running, also we use for game editing "run .sh as program" for editing, and most time
he worked in VSC not in UE editor. BUT no one from us, have a clue how to "handle" that!

Does your project have any additional plugins and dependencies?
.. "Any", of course some tiny plugins i am sure are in it, but the most UE plugins and addons ad "whatever" do not run in
ubuntu. :((
But if we not did changed the compiled game code, i as noob GUESS, that is still fine... :)

Can you succesfully stream it locally by launching the signalling server and connecting to your project on localhost?
.. Last week a normal server admin and i try to reverse engineering the "construct" to understand a bit of it.
At the end we got a connect in browser, BUT only by IP with Port, and anyway the login user - multiplayer was still not running
/ connecting.
Then it was really late night, and the freelancer needs some sleep, and it looks as he sleep now since a week.
So NOW, i have no clue if i will do roll-back some files out of a old file backup, and IF yes, which one.. ?!? :((
I have some ubuntu sys backup files, also project files, but no "totally restore backup" .

Do you have the supplied signalling server/matchmaker/SFU running?
.. Of course he build also the matchmaker and Matrix login for it, it was running excellent.
.. so it do use our 42.chat system for SignUp process, on the signup end the user do landing in the matrix. and if a user do
LogIn from the game page, he do landing in the game.. :))
/// [Jump to 10:10](https://drive.google.com/file/d/10cHOUXE9I-THgBvjYB9sj1lrCbDP2SZE/view?usp=drive_link)
Jump to 10:10

Which component is exhibiting the issue?
.. In the begin direct after the "crash" it was reporting in signaler one IP missing, and also a "multiple threads in GPU".
But that part is now running..
BUT i think, the server admin have now typed a new "start-script", perhaps that is now "not right way" as before...

If you have any crash logs/websocket information/ICE candidates exchange details, please share those and indicate when the issue occurs.
.. Logfiles and error logs we have "endless" :()

... It is as it is, we will need for future times at minimum one expert for c++ ue5 tech stuff in the team.
So if, IF the output is back and running, we will try to run a tiny "presale" to find some cash for more servers and more team.
Direct after we can start with founding a company and having then also hopefully a permanent stable team++ ... ;)

**Comment by mcottontensor** [comment] 2024-08-06 22:40
Please do not create multiple tickets for the same issue. We can continue the discussion on the original.

Dupe of #168

**Closed as completed by mcottontensor** 2024-08-06 22:40 UTC
