### ISSUE TITLE
Custom compiled streaming session disconnect: `Only found one IP` and `Error, Multiple Threads in GPU`

### ISSUE THREAD

**Issue by buschmann** [EpicGames/PixelStreamingInfrastructure#168] opened 2024-07-05 17:45 UTC
## Component your question relates to
- [XX ] Signalling server
- [ ] Frontend library
- [ ] Frontend UI library
- [ X?] Matchmaker
- [ ] SFU
- [ ] This repo
- [X? ] Other

## Background
Our tiny ubuntu 20.04 Gnome X11 / A4000 Ampere V3 / UE5 server was 200 day long running, nice UPtime. 💯 
It do serve on one IP .26 the web, and on second IP .77 it handle the Pixel Streaming. 
Actually also both is t reach in browser. So it is up and still running.
! + We did changed NO script or game-script code ! (hopefully)
! - We do run any special construct, using a lot C++ and Visual Studio and also run any own compiler script.

NOW, "Why-Ever" it do in web not connect in the browser come Click to Start >> Disconnected: . :(( 

Normal it is only to open 5x terminal as non-root, 
and to: start-signal, start-stream, start-game, NVTOP, HTOP. 
// "Easy" that i can do as noob...

By starting it do talking about some lines.:
# Only found one IP  = "suspect" but it say also "done anyway"... = perhaps there it do "split into double" ??
# Error, Multiple Threads in GPU.  = Yes, in nvtop it looks also for me as "doubble-content" is running in it. 

## Question
1) How we can fix the (of course confuse fail construct), 
2) Or can anyone help us to setup a "perfect" solution?

## Additional context
We are only a tiny indie garage production, some digital nomads...
Our Avatar, won the second/third rank on a dance-competition, 
before he learned walking.  ;))  (2/3* both have same amount of voting's) 
Here is a view about what we do... 
https://drive.google.com/drive/folders/1jIPxNCUI27wEGnk_n47_uc5ytrbFbbND

![butwhy2x2linesdoubble (1)](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/353873/c52d9948-9a18-4169-a14a-f247f6a9d78b)

buschland.eu   web    go.buschland.eu  stream ... ! Sometimes the server is OFF but never long...

**Comment by mcottontensor** [comment] 2024-08-01 01:32
I'm not sure what the question is here, there seems to be a lot going on.
Are you able to break down exactly what the issue is here?

**Comment by buschmann** [comment] 2024-08-01 04:30
In short words, we are still by the way to repair it, and no one knows "how".  :((

**Comment by mcottontensor** [comment] 2024-08-01 22:55
I can't help you if I can't understand what the problem is. Can you describe what the problem is? Can you list the steps that I can take to reproduce the issue?

**Comment by buschmann** [comment] 2024-08-02 08:37
Good morning :)
ok, actually we are on a point, that both IP`s (web and game) do anyway do response.    "Step No1" :))
Now we try to understand where and how the "login & multiplayer" parts do working ...
I hope at the weekend we will find and understand it a bit...
Did you run on matrix?  
/ With screen share and audio it is more "easy" to talk about complex chaos ...  
I am user "b" in our 42.chat

**Comment by DenisTensorWorks** [comment] 2024-08-05 04:36
Hi @buschmann, I'm closing this issue, if you still need help, please open a new issue and ensure to supply the following information, otherwise we can't assess the problem and help you.

- What UE version and PS infra versions are you using?
- What hardware/VM are you running your project on?
- Are you using the default distribution of PS and its components? If not, what changes have you made?
- When encountering the issue, please spell out step-by step exactly what you've done and where the issue occurs:
 - Is your project packaged for shipping/development? Does your project have any additional plugins and dependencies?
 - Can you succesfully stream it locally by launching the signalling server and connecting to your project on localhost?
 - Do you have the supplied signalling server/matchmaker/SFU running? Which component is exhibiting the issue?
 - If you have any crash logs/websocket information/ICE candidates exchange details, please share those and indicate when the issue occurs.

We unfortunately currently struggle to understand what the problem is and what component is exhibiting the problem.

**Closed as completed by DenisTensorWorks** 2024-08-05 04:36 UTC
Labels: question

**Comment by buschmann** [comment] 2024-08-05 08:58
Good morning ;)

What UE version and PS infra versions are you using?
.. It is UE5.1 and some tiny scripts. 

What hardware/VM are you running your project on?
.. It is a dedicated root server, ubuntu 20.04, gnome, x11, with 128gb memory, A4000gpu.

Are you using the default distribution of PS and its components? If not, what changes have you made?
.. How can i check that ? I think that is all anyway hand build for the C++ multiplayer template...

When encountering the issue, please spell out step-by step exactly what you've done and where the issue occurs:
.. Easy to explain, 200 days before i did "start-signal, start-stream" and it was running fine. 
   We changed nothing in game code or scripts for starting it. 
   So i GUESS any server updates was fail or missing or a driver update delivered the problem.

Is your project packaged for shipping/development? 
.. Oh yes, we have any external "compiler" running, also we use for game editing "run .sh as program" for editing, and most time 
   he worked in VSC not in UE editor.  BUT no one from us, have a clue how to "handle" that! 

Does your project have any additional plugins and dependencies?
.. "Any", of course some tiny plugins i am sure are in it, but the most UE plugins and addons ad "whatever" do not run in 
   ubuntu. :((
   But if we not did changed the compiled game code, i as noob GUESS, that is still fine... :) 

Can you succesfully stream it locally by launching the signalling server and connecting to your project on localhost?
.. Last week a normal server admin and i try to reverse engineering the "construct" to understand a bit of it.
  At the end we got a connect in browser, BUT only by IP with Port, and anyway the login user - multiplayer was still not running 
  / connecting. 
  Then it was really late night, and the freelancer needs some sleep, and it looks as he sleep now since a week. 
  So NOW, i have no clue if i will do roll-back some files out of a old file backup, and IF yes, which one.. ?!? :((  
  I have some ubuntu sys backup files, also project files, but no "totally restore backup" .

Do you have the supplied signalling server/matchmaker/SFU running? 
.. Of course he build also the matchmaker and Matrix login for it, it was running excellent. 
..  so it do use our 42.chat system for SignUp process, on the signup end the user do landing in the matrix. and if a user do 
   LogIn from the game page, he do landing in the game..  :))
   /// Jump to 10:10   
   [Jump to 10:10](https://drive.google.com/file/d/10cHOUXE9I-THgBvjYB9sj1lrCbDP2SZE/view?usp=drive_link)
        


Which component is exhibiting the issue?
.. In the begin direct after the "crash" it was reporting in signaler one IP missing, and also a "multiple threads in GPU".
  But that part is now running..  
  BUT i think, the server admin have now typed a new "start-script", perhaps that is now "not right way" as before...

If you have any crash logs/websocket information/ICE candidates exchange details, please share those and indicate when the issue occurs.
.. Logfiles and error logs we have "endless" :() 

... It is as it is, we will need for future times at minimum one expert for c++ ue5 tech stuff in the team.  
   So if, IF the output is back and running, we will try to run a tiny "presale" to find some cash for more servers and more team.
   Direct after we can start with founding a company and having then also hopefully a permanent stable team++ ... ;)

**Comment by mcottontensor** [comment] 2024-08-06 22:51
> When encountering the issue, please spell out step-by step exactly what you've done and where the issue occurs:
> .. Easy to explain, 200 days before i did "start-signal, start-stream" and it was running fine.
> We changed nothing in game code or scripts for starting it.
> So i GUESS any server updates was fail or missing or a driver update delivered the problem.

Is this the actual issue you are facing? Streaming was originally working some time ago and now it does not work?
You will need to provide us logs or error messages so we can triage the problem. Simply stating it does not work is not helpful.

Did you update the Pixel Streaming plugin, the Infra repo or the UE engine over that time? What were the versions that last worked, if you know?

When you try to open a stream now, what happens? Are there error messages in the UE logs? Are there error messages in the signalling server? Are there error messages in the browser or browser console?

If you can provide these details and show that the problem is within the Pixel Streaming ecosystem then we can reopen this issue. Currently this does not sound like a Pixel Streaming issue.
